# Generated by Django 4.0.1 on 2022-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flightinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flightnumber', models.IntegerField()),
                ('Destination', models.CharField(max_length=100)),
                ('Distance', models.CharField(max_length=100)),
                ('Fuelquantity', models.IntegerField()),
            ],
        ),
    ]
